spring:
  application:
    name: Perseo

  datasource:
    url: jdbc:mysql://localhost:3306/perseo
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

# JWT Configuration
jwt:
  secret: eW91cl9zZWNyZXRfa2V5X2hlcmU=
  expiration: 3600000
